### ISSUE TITLE
First drilldown option always requires second click

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/tesseract-ui#3]
Clicking on whichever is the top option clears the menu on first click and then actually selects the item on the second click.

<img width="660" alt="Screen Shot 2019-07-01 at 12 13 59 PM" src="https://user-images.githubusercontent.com/252276/60451338-ce312500-9bf9-11e9-91de-0c6088ab11d5.png">

**Comment by frabarz** [comment]
I noticed this problem from the start, but it's a weird default behavior of blueprint I can't find how to disable. I found other issues with the same problem, so I'll try their solutions.

**Comment by alexandersimoes** [comment]
Great that you're aware! Just want to keep it here so it's documented.

**Comment by frabarz** [comment]
the cause is a known bug that automatically focuses the first focuseable thing in the Popover content
the fix was included in the middleware update, basically consists in setting `autofocus={false}` on the Popover components
