### ISSUE TITLE
Can't copy/paste text in data table

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/tesseract-ui#5]
This may be related to #1 but now that the text is selectable, my use case is wanting to select a few rows, copy them and paste them into an email to share with someone else. Currently when I use either the keyboard shortcut (cmd-C) or the file menu (Edit > Copy) and paste, nothing appears. I'm not sure how difficult this is to support but otherwise I have to open the tesseract api url and copy the data from there.

**Comment by frabarz** [comment]
fixed on c3a7b0aa5bf1dc501578d3c2e25a8580eb5a147e
